server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: false # EUC-KR 인코딩 받기위해 설정함.
  error:
    include-exception: false
    whitelabel:
      enabled: false  
spring:
  profiles:
    active: local
  #데이터 베이스 세팅
  datasource:
    url: jdbc:mysql://mysql-j.cc3rp9hbh2xf.ap-northeast-2.rds.amazonaws.com:3306/jalldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:log4jdbc:mysql://mysql-j.cc3rp9hbh2xf.ap-northeast-2.rds.amazonaws.com:3306/jalldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: jmaster1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #thymeleaf 설정
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML5
    cache: false
# 실행되는 쿼리 콘솔에 출력
# 콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
# 쿼리에 물음표로 출력되는 바인드 파라미터 출력
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
#마이바티스 세팅
mybatis: 
  type-aliases-package: com.project.projectmay.**.*
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    call-setters-on-nulls: true # 가져온 값이 null일때 setter나 맵의 put 메소드를 호출할지를 명시 Map.keySet() 이나 null값을 초기화
    map-underscore-to-camel-case: true # 전통적인 데이터베이스 칼럼명 형태인 A_COLUMN을 CamelCase형태의 자바 프로퍼티명 형태인 aColumn으로 자동으로 매핑하도록 함
  
  
  
  
  